In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[ "the glass of milk",
"the glass of juice",
"the cup of tea",
"I am a good boy",
"I am a good developer",
"understand the meaning of words",
"your videos are good"]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# define vocabulary size
voc_size=10000

In [5]:
for words in sent:
  print(words)

the glass of milk
the glass of juice
the cup of tea
I am a good boy
I am a good developer
understand the meaning of words
your videos are good


In [9]:
#one hot representation

one_hot_representation=[one_hot(words,voc_size) for words in sent]
one_hot_representation

[[845, 9629, 5966, 7974],
 [845, 9629, 5966, 6337],
 [845, 656, 5966, 6485],
 [6193, 5272, 6355, 8915, 3787],
 [6193, 5272, 6355, 8915, 7584],
 [9950, 845, 9203, 5966, 922],
 [8613, 4260, 5211, 8915]]

In [10]:
# it means at the index 845 only i have the word "the" remianing else numbers are 0 ->sparse matrix

from tensorflow.keras import Sequential
from tensorflow.keras.utils import pad_sequences

import numpy as np



In [11]:
sent_len=8
embedded_docs=pad_sequences(one_hot_representation,maxlen=sent_len,padding='pre')

In [12]:
embedded_docs

array([[   0,    0,    0,    0,  845, 9629, 5966, 7974],
       [   0,    0,    0,    0,  845, 9629, 5966, 6337],
       [   0,    0,    0,    0,  845,  656, 5966, 6485],
       [   0,    0,    0, 6193, 5272, 6355, 8915, 3787],
       [   0,    0,    0, 6193, 5272, 6355, 8915, 7584],
       [   0,    0,    0, 9950,  845, 9203, 5966,  922],
       [   0,    0,    0,    0, 8613, 4260, 5211, 8915]], dtype=int32)

In [16]:
# feature representation - 300 dimensions means represnt my each word with 300 dimensions

from tensorflow.keras.layers import Dense,Embedding

dim=10 # so now after thiss every word is then represented by 10 dimensions

model=Sequential()
model.add(
    Embedding(
        input_dim=voc_size,
        output_dim=dim,
        input_shape=(sent_len,)
    )
)
model.compile(optimizer='adam')

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [17]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
embedded_docs

array([[   0,    0,    0,    0,  845, 9629, 5966, 7974],
       [   0,    0,    0,    0,  845, 9629, 5966, 6337],
       [   0,    0,    0,    0,  845,  656, 5966, 6485],
       [   0,    0,    0, 6193, 5272, 6355, 8915, 3787],
       [   0,    0,    0, 6193, 5272, 6355, 8915, 7584],
       [   0,    0,    0, 9950,  845, 9203, 5966,  922],
       [   0,    0,    0,    0, 8613, 4260, 5211, 8915]], dtype=int32)

In [21]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 237ms/step


array([[[ 0.02923589, -0.01263915, -0.00620499, -0.03523571,
          0.01535425, -0.03883672, -0.04525945, -0.01115354,
          0.0477686 ,  0.00674503],
        [ 0.02923589, -0.01263915, -0.00620499, -0.03523571,
          0.01535425, -0.03883672, -0.04525945, -0.01115354,
          0.0477686 ,  0.00674503],
        [ 0.02923589, -0.01263915, -0.00620499, -0.03523571,
          0.01535425, -0.03883672, -0.04525945, -0.01115354,
          0.0477686 ,  0.00674503],
        [ 0.02923589, -0.01263915, -0.00620499, -0.03523571,
          0.01535425, -0.03883672, -0.04525945, -0.01115354,
          0.0477686 ,  0.00674503],
        [-0.04815531, -0.02824601, -0.03739155,  0.01991988,
          0.04681064,  0.00037984,  0.00934771,  0.02973232,
         -0.00511159, -0.00342856],
        [ 0.02241122,  0.03247646, -0.04739172,  0.00359312,
         -0.03672942,  0.01806445,  0.03005305, -0.03839989,
          0.00801871, -0.04125401],
        [-0.01875924,  0.02048627, -0.02102156, -0.0